[package]
name = "rusterizer"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]

[lib]
name = "vulkan_rusterizer"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
log = "0.3"
env_logger = "0.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
